import React from 'react';
import type { WorkedExampleData } from '../types/learning';
import { SECTION_QUIZZES } from '../data/quizData';
import { ConceptCard } from '../components/pedagogy/ConceptCard';
import { MisconceptionCard } from '../components/pedagogy/MisconceptionCard';
import { ExamTip } from '../components/pedagogy/ExamTip';
import { KeyTakeaway } from '../components/pedagogy/KeyTakeaway';
import { DeepDive } from '../components/pedagogy/DeepDive';
import { WorkedExample } from '../components/pedagogy/WorkedExample';
import { Quiz } from '../components/pedagogy/Quiz';
import { FormulaCard } from '../components/math/FormulaCard';
import { NewtonFirstSim } from '../components/simulations/NewtonFirstSim';

interface NewtonFirstLawProps {
  onNextSection: () => void;
  onAnswerSubmitted?: (isCorrect: boolean) => void;
  savedAnswer?: { selectedOptionId: string; isCorrect: boolean };
}

const WORKED_EXAMPLE_N1: WorkedExampleData = {
  id: 'we-n1',
  problemStatement:
    'An aircraft of mass 45,000 kg flies horizontally at a constant cruising altitude and constant velocity of 250 m/s through calm air. The engine produces a forward thrust of 68,000 N. (a) Determine the magnitude of the air resistance (drag force). (b) Determine the upward aerodynamic lift force generated by the wings. (Take g = 9.81 m/s²)',
  givenData: [
    { label: 'Mass', value: '45,000 kg', symbol: 'm' },
    { label: 'Velocity', value: '250 m/s (constant)', symbol: 'v' },
    { label: 'Engine Thrust', value: '68,000 N', symbol: 'F_{\\text{thrust}}' },
    { label: 'Gravity', value: '9.81 m/s²', symbol: 'g' },
  ],
  steps: [
    {
      stepNumber: 1,
      title: 'State the Condition of Motion',
      explanation:
        'The aircraft moves in a straight line at constant speed and constant altitude. Therefore, its acceleration is zero: a = 0.',
      mathLaTeX: '\\vec{a} = 0 \\implies \\Sigma\\vec{F} = 0',
      highlightText: 'Translational equilibrium applies in both horizontal and vertical directions.',
    },
    {
      stepNumber: 2,
      title: 'Apply Horizontal Force Balance (ΣFx = 0)',
      explanation:
        'In the horizontal axis, the forward engine thrust is opposed by the backward aerodynamic drag force D.',
      mathLaTeX: '\\Sigma F_x = F_{\\text{thrust}} - D = 0',
    },
    {
      stepNumber: 3,
      title: 'Calculate Air Resistance (Drag)',
      explanation: 'Since ΣFx = 0, the drag force must exactly equal the forward thrust.',
      mathLaTeX: 'D = F_{\\text{thrust}} = 68{,}000\\text{ N}',
    },
    {
      stepNumber: 4,
      title: 'Apply Vertical Force Balance (ΣFy = 0)',
      explanation:
        'In the vertical axis, the upward aerodynamic lift force L is opposed by the downward gravitational weight W = mg.',
      mathLaTeX: '\\Sigma F_y = L - mg = 0 \\implies L = mg',
    },
    {
      stepNumber: 5,
      title: 'Calculate Lift Force',
      explanation: 'Multiply the mass of the aircraft by standard gravitational acceleration.',
      mathLaTeX: 'L = 45{,}000\\text{ kg} \\times 9.81\\text{ m/s}^2 = 441{,}450\\text{ N}',
    },
  ],
  finalAnswer: {
    symbol: 'D \\text{ and } L',
    value: 'Drag = 68,000 N (backward), Lift = 441,450 N (upward)',
    unit: '',
    mathLaTeX: 'D = 68.0\\text{ kN},\\quad L = 441.5\\text{ kN}',
  },
};

export const NewtonFirstLaw: React.FC<NewtonFirstLawProps> = ({
  onNextSection,
  onAnswerSubmitted,
  savedAnswer,
}) => {
  const quiz = SECTION_QUIZZES['newton-first-law'];

  const takeaways = [
    { id: 't1', text: 'Zero net force means constant velocity (a = 0)', mathFormula: '\\Sigma\\vec{F} = 0 \\iff \\vec{v} = \\text{const}' },
    { id: 't2', text: 'Rest is simply a special case of constant velocity (v = 0)' },
    { id: 't3', text: 'Forces cause changes in velocity (acceleration), NOT velocity itself' },
    { id: 't4', text: 'Inertia is the natural property of mass to resist acceleration' },
  ];

  return (
    <div className="space-y-8 animate-fadeIn">
      {/* Topic Title Header */}
      <div className="border-b border-slate-800 pb-4">
        <div className="flex items-center gap-2 text-xs font-mono text-cyan-400 mb-1">
          <span>Topic 1 of 9</span>
          <span>•</span>
          <span>IB DP Physics A.2.1</span>
        </div>
        <h1 className="text-2xl sm:text-3xl font-extrabold text-white font-display">
          Newton's First Law of Motion: The Law of Inertia
        </h1>
        <p className="text-sm text-slate-400 mt-1">
          How translational equilibrium governs uniform motion in a straight line and states of rest.
        </p>
      </div>

      {/* 1. Concept Section */}
      <div className="grid grid-cols-1 md:grid-cols-3 gap-4">
        <div className="md:col-span-2">
          <ConceptCard title="The Principle of Inertia" variant="cyan">
            <p>
              Isaac Newton's First Law states: <em>"An object will remain at rest or continue to move with constant velocity in a straight line unless acted upon by a non-zero resultant (net) external force."</em>
            </p>
            <p className="mt-2 text-slate-300">
              This completely revolutionized mechanics by discarding the ancient view that force is needed to keep things moving. In truth, a body with no net force acting on it possesses <strong>inertia</strong>—the intrinsic tendency to maintain its current state of motion.
            </p>
          </ConceptCard>
        </div>

        <div>
          <FormulaCard
            title="Equilibrium Condition"
            mathLaTeX="\Sigma\vec{F} = 0 \implies \vec{v} = \text{constant}"
            description="When vector sum of all forces is zero, acceleration is strictly zero."
            variables={[
              { symbol: '\\Sigma\\vec{F}', name: 'Net Force Vector', unit: 'N' },
              { symbol: '\\vec{v}', name: 'Velocity Vector', unit: 'm/s' },
              { symbol: '\\vec{a}', name: 'Acceleration', unit: '0 m/s²' },
            ]}
          />
        </div>
      </div>

      {/* 2. Interactive Simulation */}
      <div>
        <NewtonFirstSim />
      </div>

      {/* 3. Common Misconception Callout */}
      <MisconceptionCard
        myth="If an object is moving, there must be a forward force pushing it. Zero net force means zero velocity (the object must be stopped)."
        reality="Zero net force means ZERO ACCELERATION (a = 0), which means velocity is CONSTANT. An object can move at 10,000 m/s with zero net force!"
        scientificExplanation="Force is required only to CHANGE velocity (to accelerate, decelerate, or change direction). In the absence of resistance or external forces, motion continues indefinitely due to mass inertia."
        whyItMatters="In IB Exam Paper 1, questions frequently test rockets in space or gliders on air tracks moving at steady speeds where ΣF = 0."
      />

      {/* 4. IB Exam Tip */}
      <ExamTip
        title="Constant Velocity = Zero Net Force"
        tip="Whenever an IB question mentions 'constant speed in a straight line', 'steady velocity', or 'terminal speed', immediately write ΣF = 0. All forward forces must exactly equal all resistive forces."
        paperType="Paper 2 (Structured)"
        warning="Do not confuse 'speed is constant' in a circle (where direction changes, so ΣF ≠ 0) with straight-line motion!"
      />

      {/* 5. Worked Example (Progressive Reveal) */}
      <WorkedExample data={WORKED_EXAMPLE_N1} />

      {/* 6. Check Yourself Quiz */}
      <Quiz
        question={quiz}
        savedAnswer={savedAnswer}
        onAnswerSubmitted={onAnswerSubmitted}
        onNextSection={onNextSection}
      />

      {/* 7. Key Takeaway Badges */}
      <KeyTakeaway takeaways={takeaways} />

      {/* 8. Deep Dive (Expandable) */}
      <DeepDive
        title="Inertial Reference Frames & Galilean Relativity"
        subtitle="Why Newton's 1st Law only holds in non-accelerating frames of reference"
        ibLevel="HL"
        equations={[
          '\\vec{r}\' = \\vec{r} - \\vec{v}_0 t',
          '\\vec{a}\' = \\vec{a} \\quad\\text{(Invariance of Acceleration)}',
        ]}
      >
        <p>
          Newton’s laws of motion are valid only in <strong>inertial frames of reference</strong>—reference frames that are not accelerating.
        </p>
        <p className="mt-2">
          Inside an accelerating vehicle (a non-inertial frame), an object on the floor appears to accelerate backwards without any real physical force pushing it (a "fictitious" or inertial force). The principle of Galilean relativity states that the laws of Newtonian mechanics are identical in all inertial reference frames moving at constant relative velocity.
        </p>
      </DeepDive>
    </div>
  );
};
